# Generated by Django 5.2 on 2026-06-26 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. Instagram, YouTube, X, direct', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
